### ISSUE TITLE
AutoSlabs Compatibility Issue

### ISSUE THREAD

**Issue by Ultimushadow** [Leximon/Fluidlogged#13]
Hey there, I was attempting to load both these mods, but quickly found that the game crashed whenever the player placed a new slab. I'll be making an issue report with AutoSlabs as well, mod information and crash report is below:

Minecraft: 1.20.1
Fabric: 0.14.21/0.14.22
AutoSlabs: 1.1.2
Fluidlogged: 1.2.1

Crash Report: [crash-2023-08-24_04.50.54-client.txt](https://github.com/Leximon/Fluidlogged/files/12428113/crash-2023-08-24_04.50.54-client.txt)

The crash is client-side and only shows up when placing a slab from what I can tell, nothing interesting in the log but I'll link it if you would like. I noticed that in said crash report it mentions removing fluid when the block is a double slab, in my testing I found that AutoSlabs keeps the fluid when double slabbed but I did also notice an issue report here mentioning fluid retention, so I imagine you'll have a better idea on what's going on there.

**Comment by Leximon** [comment]
Fixed in `2.0.0-beta1` :)
