### ISSUE TITLE
No option to disable fluids passing through blocks

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Leximon/Fluidlogged#15]
The description says:
> If you don't like some features such as, fluids passing through blocks, you can disable this in the config.

However I don't see any option to disable fluids passing through blocks:
```json
{
  "compatibilityMode": false,
  "fluids": [],
  "disabledEnforcedFluids": []
}
```
<details>

<summary><strong>Fluid settings screenshot</strong></summary>

![list of fluids with check-boxes to their left](https://github.com/Leximon/Fluidlogged/assets/618276/70fd1d16-051d-492e-bb05-5414a5789444)

</details>
Using the 1.2.0 Fabric version.

**Comment by Leximon** [comment]
This is only a feature for version 2.0.0 and above.
![grafik](https://github.com/Leximon/Fluidlogged/assets/39879662/558f1cbf-af28-4184-947e-92a7b5823950)

**Comment by supersaiyansubtlety** [comment]
Oh oops, sorry
