### ISSUE TITLE
[incompatability] FL, IP and possible unknown 3rd mod

### ISSUE THREAD

**Issue by AlienXtream** [Leximon/Fluidlogged#16]
minecraft 1.20.1
fabric 0.14.22
FL 2.0.1-beta 2

for reasons i am having trouble working out the game crashes when creating a world with FL, IP, and a bunch of other mods. the reason im even suspecting something with IP is that the crash is, ironically, from IP but only when FL is installed too. i tested the mod in a control setting with IP, FL, and their dependencies (sodium included because NVidia card) and all worked as expected so i know its at least not specifically a direct compatability. looking at the modrinth page said to report compatability issues to you, not the other mod(s) in question so i hope this is acceptable. i apologise if this is not actually a FL crash (though i hope you understand why i would suspect it, given it works without FL but not with.

if you need more info i can try and provide it. again, i apologise in advance if i am mistaken in my assumptions

[crash-2023-10-17_09.42.35-client.txt](https://github.com/Leximon/Fluidlogged/files/12922513/crash-2023-10-17_09.42.35-client.txt)

**Comment by Leximon** [comment]
Have you tried removing only Fluidlogged from your large modpack and tested if that solves the issue? If the game still crashes then it's very likely not an issue with my mod.

**Comment by AlienXtream** [comment]
i have. in fact im playing it now (with FL disabled). im not surprised it crashed, more so that there seems to be at least 3rd mod involved that i cant identify (and dealing with interconnected dependencies is a headache. at least reloaading/launching is WAY faster with fabric... XD). anyway. if you like i can provide a prism launcher pack if you think that'd help?

**Comment by Leximon** [comment]
Well in that case, I would say that is not my responsibility anymore because it's not an issue with fluidlogged.

**Comment by AlienXtream** [comment]
thats fair enough. i will continue to test the mod when i can and if i find anything that is more conclusive (and suggests it is either a FL issue or compatability problem) i will update you. :)

**Comment by AlienXtream** [comment]
as a developer/programmer im sure the phrase "it works on my system" can only be topped with "it started working now"... redownloaded the mod and it works... same version from modrinth via prism launcher... fun... sorry for waisting your time with this.

**Comment by Leximon** [comment]
Don't worry, I don't really have a problem with this.
