### ISSUE TITLE
Strange waterlogged blocks in the world

### ISSUE THREAD

**Issue by DracoTijandor** [Leximon/Fluidlogged#2]
Since I installed this mod some blocks from other mods will be generated with water around it.

Some examples: Better End Flavorite Fence in the Ender Dragon fight and Waystones.

Minecraft: 1.18.2
Fabric: 0.14.6
Fluidlogged: 1.0.1
Mode: Compatibility (becaus of origins is also installed)

**Comment by Leximon** [comment]
Fixed in the newest version of fluidlogged.
Thanks for reporting! :)
