### ISSUE TITLE
[1.18.2 Forge] [Compatibility?] Non-water fluid-logged blocks are not detected as source blocks by other mods

### ISSUE THREAD

**Issue by AerosAtar** [Leximon/Fluidlogged#4]
As the description says - blocks 'logged with non-water fluids are not detected as being source blocks of that fluid for the purposes of interaction by other mods.

For example: Placing a **Thermal Expansion** Igneous Extruder with a water-logged stair on one side and a lava-logged stair on the other will detect the water, but not the lava. Removing the latter stair and placing a lava source normally allows the machine to detect both source blocks and function. It doesn't matter what the block being 'logged is - it doesn't detect it as a lava source block.

I suspect this is complicated by the need to prevent fluid->solid transformation interactions (lava->obsidian/stone when coming in contact with water) on 'logged blocks, but it would be amazing if it could be made to recognise the 'logged blocks as being source blocks for everything else.

**Comment by Pikabyte** [comment]
So...I'm not really sure how I'd go about implementing such a fix. More than just preventing weird interactions in logged blocks, I also don't know how I would make sure it would work with every modded fluid interaction. I also think that this feature would be pretty low priority.
I'm sure I could figure it out if I was given time, but I kind of lost motivation to continue working on this project. In concept, the idea works great, but the reality is that the mod is horrible for performance(even more so than many of the mega-mods out there on curseforge), and despite such, it has very little to show for it. Thus, I'm not too proud of the implementation to begin with, and alternative implementations would require me to rewrite significant portions of the game.
On top of all that, the 1.19.1 update really killed my motivation to continue to support this game. Thus, I've recently decided that I would rather cut all ties with Minecraft to work on other projects. As such, I don't think this will get fixed any time soon. I suppose I should make a statement on the curseforge page. Sorry to bring bad news, and thanks for giving the mod a try. I will put a notice on the curseforge page soon.
