### ISSUE TITLE
Forge compat for cross mod compatibility could use forge's IMC system.

### ISSUE THREAD

**Issue by ExpensiveKoala** [Leximon/Fluidlogged#9]
Forge has a system for "Inter Mod Communication" (or IMC). This allows any forge mod to add support (of adding their fluid IDs) without a dependency to this mod. Similarly to how the fabric support of "custom" in fabric.mod.json adds support.

If you are unfamiliar with forge's IMC system, DarkHax has a tutorial on it here: https://darkhax.net/2017/10/inter-mod-coms

**Comment by Leximon** [comment]
Thanks, I will take a look at it!

**Comment by Leximon** [comment]
Not relevant anymore for version `2.0.0-beta1`
